### ISSUE TITLE
Replace StarterBot .bot file with appsettings.json

### ISSUE THREAD

**Issue by fvarga01** [martinkearn/Bot-Starter-Template#12]
Pre https://docs.microsoft.com/en-us/azure/bot-service/bot-file-basics?view=azure-bot-service-4.0&tabs=csharp

"Prior to the Bot Framework SDK 4.3 release, we offered the .bot file as a mechanism to manage resources. However, going forward we recommend that you use appsettings.json or .env file for managing these resources. Bots that use .bot file will continue to work for now even though the .bot file has been deprecated."

**Comment by martinkearn** [comment]
Thanks for the feedback.

The .bot file is still required for use with the emulator which is why it is included. 

If you look inside the .bot file, you'll see that no secrets are stored there and there are placeholders for all the secrets in `AppSettings.json` which is the best practice for v4.3.

In actual fact you should use `secrets.json` to store secrets but that is not included in the project because it is stored outside the project folder by convention.

Does this address your question? Feel free to comment further if not.

Thanks
